### ISSUE TITLE
Does not give response 

### ISSUE THREAD

**Issue by CarlosTwT** [hacxk/WhatsappBotTemplate#1]
It connects but there is no response

**Comment by hacxk** [comment]
No It work fine

**Comment by hacxk** [comment]
> It connects but there is no response

Are you scanned QR Code/Pairing Code and obtained session?

**Comment by CarlosTwT** [comment]
> > Se conecta pero no hay respuesta.
> 
> ¿Escaneó el código QR/código de emparejamiento y obtuvo la sesión?

The bot connects but does not respond to commands

**Comment by hacxk** [comment]
> > > Se conecta pero no hay respuesta.
> > 
> > 
> > ¿Escaneó el código QR/código de emparejamiento y obtuvo la sesión?
> 
> The bot connects but does not respond to commands

Bro try sending /menu or !menu
